<ouc:editor wysiwyg="no"/>
		<li>
			<a href="#" title="facebook"><span class="platform-name">facebook</span><i class="fa fa-facebook" aria-hidden="true"></i></a>
		</li>
		<li>
			<a href="#" title="twitter"><span class="platform-name">twitter</span><i class="fa fa-twitter" aria-hidden="true"></i></a>
		</li>
		<li>
			<a href="#" title="instagram"><span class="platform-name">instagram</span><i class="fa fa-instagram" aria-hidden="true"></i></a>
		</li>
		<li>
			<a href="#" title="snapchat"><span class="platform-name">snapchat</span><i class="fa fa-snapchat" aria-hidden="true"></i></a>
		</li>
		<li>
			<a href="#" title="youtube-play"><span class="platform-name">youtube-play</span><i class="fa fa-youtube-play" aria-hidden="true"></i></a>
		</li>
		<li>
			<a href="#" title="linkedin"><span class="platform-name">linkedin</span><i class="fa fa-linkedin" aria-hidden="true"></i></a>
		</li>