<ouc:editor wysiwyg="no"/>
<div class="col-md-3 col-sm-6 col-xs-12">
	<dl>
		<dt>About UGA</dt>
		<dd><a href="http://visit.uga.edu/">Visit UGA</a></dd>
		<dd><a href="https://ovpi.uga.edu/about-ovpi/ovpi-units/extended-campuses">Extended Campuses</a></dd>
		<dd><a href="http://www.architects.uga.edu/maps/current">Campus Map</a></dd>
		<dd><a href="http://calendar.uga.edu/">Master Calendar</a></dd>
		<dd><a href="http://www.hr.uga.edu/employees/employment">Employment</a></dd>
	</dl>		
</div>
<div class="col-md-3 col-sm-6 col-xs-12">
	<dl>
		<dt>Helpful Links</dt>
		<dd><a href="https://my.uga.edu">MyUGA</a></dd>
		<dd><a href="https://athena.uga.edu/">Athena</a></dd>
		<dd><a href="https://www.elc.uga.edu/">eLearning Commons</a></dd>
		<dd><a href="http://www.bulletin.uga.edu/">UGA Bulletin</a></dd>
		<dd><a href="http://www.reg.uga.edu/calendars">Academic Calendars</a></dd>
	</dl>
</div>
<div class="col-md-3 col-sm-6 col-xs-12">
	<dl>
		<dt>Student Life</dt>
		<dd><a href="https://ugamail.uga.edu/">UGA Mail</a></dd>
		<dd><a href="http://foodservice.uga.edu/">Food Services</a></dd>
		<dd><a href="http://dos.uga.edu/">Campus Life</a></dd>
		<dd><a href="http://www.recsports.uga.edu/">Recreational Sports</a></dd>
		<dd><a href="https://studentacct.uga.edu">Student Accounts</a></dd>
	</dl>
</div>
<div class="col-md-3 col-sm-6 col-xs-12">
	<dl>
		<dt>Helpful Links</dt>
		<dd><a href="http://osfa.uga.edu/">Financial Aid</a></dd>
		<dd><a href="http://international.uga.edu/">International Education</a></dd>
		<dd><a href="http://honors.uga.edu/">Honors Program</a></dd>
		<dd><a href="http://www.libs.uga.edu/">Library</a></dd>
	</dl>
</div>
