<ouc:editor wysiwyg="no"/>
<form accept-charset="UTF-8" action="/search" method="get">
	<div class="input-group">
		<label for="search-query" class="sr-only sr-only-focusable">Search site</label>
		<input id="search-query" type="text" name="q" class="form-control" placeholder="search site"/>
		<span class="input-group-btn">
			<button id="search-button" type="submit" class="btn btn-default">
				<span class="glyphicon glyphicon-search" aria-hidden="true"></span>
				<span class="sr-only sr-only-focusable">Search</span>
			</button>
		</span>
	</div>
</form>